name: geo
channels:
  - conda-forge
  - defaults
dependencies:
  - _libavif_api=1.3.0
  - affine=2.4.0
  - annotated-types=0.6.0
  - anyio=4.10.0
  - aom=3.9.1
  - attrs=25.4.0
  - backports.zstd=1.2.0
  - blinker=1.9.0
  - blosc=1.21.6
  - branca=0.8.2
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - cairo=1.18.4
  - certifi=2025.11.12
  - charset-normalizer=3.4.4
  - click=8.3.1
  - click-plugins=1.1.1.2
  - cligj=0.7.2
  - colorama=0.4.6
  - contourpy=1.3.3
  - cycler=0.12.1
  - dav1d=1.2.1
  - deprecation=2.1.0
  - expat=2.7.3
  - fiona=1.10.1
  - flask=3.1.2
  - flask-cors=6.0.1
  - folium=0.20.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.61.1
  - freeglut=3.8.0
  - freetype=2.14.1
  - freexl=2.0.0
  - fribidi=1.0.16
  - gdal=3.11.4
  - geopandas=1.1.1
  - geopandas-base=1.1.1
  - geos=3.10.6
  - geotiff=1.7.0
  - gotrue=2.12.4
  - graphite2=1.3.14
  - h11=0.16.0
  - h2=4.3.0
  - harfbuzz=10.4.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.27.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - iniconfig=2.1.0
  - itsdangerous=2.2.0
  - jinja2=3.1.6
  - joblib=1.5.3
  - jpeg=9e
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libarchive=3.8.2
  - libavif=1.3.0
  - libavif16=1.3.0
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libcurl=8.17.0
  - libdeflate=1.22
  - libexpat=2.7.3
  - libffi=3.4.4
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgdal-core=3.11.4
  - libglib=2.84.4
  - libhwloc=2.12.1
  - libiconv=1.18
  - libkml=1.3.0
  - liblapack=3.11.0
  - libopenjpeg=2.5.4
  - libpng=1.6.53
  - libspatialite=5.1.0
  - libsqlite=3.51.1
  - libssh2=1.11.1
  - libtiff=4.7.1
  - libwebp-base=1.6.0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxml2=2.13.9
  - libzlib=1.3.1
  - llvm-openmp=21.1.8
  - lz4-c=1.9.4
  - mapclassify=2.10.0
  - markupsafe=3.0.3
  - matplotlib-base=3.10.8
  - minizip=4.0.6
  - mkl=2025.3.0
  - multidict=6.7.0
  - munkres=1.1.4
  - networkx=3.6.1
  - numpy=2.3.5
  - openssl=3.6.0
  - packaging=25.0
  - pandas=2.3.3
  - pcre2=10.46
  - pillow=12.0.0
  - pip=25.3
  - pixman=0.46.4
  - pluggy=1.5.0
  - postgrest=2.25.0
  - proj=9.3.1
  - propcache=0.4.1
  - pydantic=2.12.4
  - pydantic-core=2.41.5
  - pygments=2.19.2
  - pyjwt=2.10.1
  - pyogrio=0.11.1
  - pyparsing=3.2.5
  - pyproj=3.6.1
  - pysocks=1.7.1
  - pytest=8.4.2
  - pytest-mock=3.15.1
  - python=3.11.14
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.3
  - python_abi=3.11
  - pytz=2025.2
  - qhull=2020.2
  - rasterio=1.4.4
  - rav1e=0.7.1
  - realtime=2.25.0
  - requests=2.32.5
  - scikit-learn=1.8.0
  - setuptools=80.9.0
  - shapely=2.1.2
  - six=1.17.0
  - snappy=1.2.2
  - sniffio=1.3.1
  - sqlite=3.51.0
  - storage3=2.25.0
  - strenum=0.4.15
  - supabase=2.25.0
  - supabase-auth=2.25.0
  - supabase-functions=2.25.0
  - supafunc=0.10.2
  - svt-av1=3.1.2
  - tbb=2022.3.0
  - threadpoolctl=3.6.0
  - tk=8.6.15
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - unicodedata2=17.0.0
  - uriparser=0.9.8
  - urllib3=2.6.2
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - websockets=15.0.1
  - werkzeug=3.1.3
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - xerces-c=3.3.0
  - xyzservices=2025.11.0
  - xz=5.6.4
  - yarl=1.22.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - python-dotenv==1.2.1
      - scipy==1.16.3
prefix: C:\Users\ainsi\miniconda3\envs\geo
